Repository mikanparade/calmikan, pull requests merged in 2023-08, with the labels that each got.

#17 コミット時にLintが走るようにする
  .github/workflows/main.yml
Labels: enhancement

#19 fix: gh-pages.ymlで pnpm install --frozen-lockfile
  .github/workflows/gh-pages.yml
Labels: bug

#16 chore: Enable design system
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: enhancement, area-fundamental

#26 Fundamentalsの完成
  src/app/fundamentals/Button.tsx
  src/app/fundamentals/Icon.tsx
  src/app/fundamentals/InputText.tsx
  src/app/fundamentals/List.tsx
  src/app/fundamentals/Property.tsx
  src/app/fundamentals/RadioButton.tsx
  src/app/fundamentals/Text.tsx
  src/app/page.tsx
  src/app/sections/EventEditor.tsx
Labels: enhancement, area-fundamental

#28 add: type definitions
  src/app/types/IEvent.ts
  src/app/types/IMonthCalendar.ts
  src/app/types/TLeeway.ts
Labels: enhancement, area-fundamental

#31 colorNum の型を数値から文字に
  src/app/fundamentals/Text.tsx
Labels: bug, area-fundamental

#32 余裕度を表すアイコンを追加
  src/app/components/LeewayIndicator.tsx
Labels: enhancement, area-part

#35 テキスト付きの余裕度を表すアイコンを追加
  src/app/parts/LeewayIndicatorWithText.tsx
Labels: enhancement, area-part
